// <auto-generated />
using System;
using ERP.Authentication.DataService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Authentication.DataService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240314231417_intial")]
    partial class intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("ERP.Authentication.Core.Entity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aacf9a50-e18f-41e8-bbf2-7c2c2d05c32b"),
                            AddedDate = new DateTime(2024, 3, 14, 23, 14, 17, 523, DateTimeKind.Utc).AddTicks(8962),
                            Password = "admin",
                            Role = "Adminstrator",
                            Status = 0,
                            UpdateDate = new DateTime(2024, 3, 14, 23, 14, 17, 523, DateTimeKind.Utc).AddTicks(8964),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("87139f4a-33f5-4b7b-907a-1f63776e2244"),
                            AddedDate = new DateTime(2024, 3, 14, 23, 14, 17, 523, DateTimeKind.Utc).AddTicks(8967),
                            Password = "user",
                            Role = "User",
                            Status = 0,
                            UpdateDate = new DateTime(2024, 3, 14, 23, 14, 17, 523, DateTimeKind.Utc).AddTicks(8967),
                            UserName = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
